# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: First Test Site
email: alexgrahambowman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site used to learn coding.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codetestbase.com" # the base hostname & protocol for your site
twitter_username: alexgb87
github_username:  alexgb87

# Build settings
markdown: kramdown
